// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// CryptoProvider is an autogenerated mock type for the CryptoProvider type
type CryptoProvider struct {
	mock.Mock
}

// DecryptSymmetric provides a mock function with given fields: ciphertext, nonce, key
func (_m *CryptoProvider) DecryptSymmetric(ciphertext []byte, nonce []byte, key []byte, aad []byte) ([]byte, error) {
	ret := _m.Called(ciphertext, nonce, key, aad)

	if len(ret) == 0 {
		panic("no return value specified for DecryptSymmetric")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte, []byte) ([]byte, error)); ok {
		return rf(ciphertext, nonce, key, aad)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte, []byte) []byte); ok {
		r0 = rf(ciphertext, nonce, key, aad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, []byte, []byte) error); ok {
		r1 = rf(ciphertext, nonce, key, aad)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptSymmetric provides a mock function with given fields: plaintext, key
func (_m *CryptoProvider) EncryptSymmetric(plaintext []byte, key []byte, aad []byte) ([]byte, []byte, error) {
	ret := _m.Called(plaintext, key, aad)

	if len(ret) == 0 {
		panic("no return value specified for EncryptSymmetric")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) ([]byte, []byte, error)); ok {
		return rf(plaintext, key, aad)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) []byte); ok {
		r0 = rf(plaintext, key, aad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, []byte) []byte); ok {
		r1 = rf(plaintext, key, aad)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func([]byte, []byte, []byte) error); ok {
		r2 = rf(plaintext, key, aad)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SignEd25519 provides a mock function with given fields: data, privKey
func (_m *CryptoProvider) SignEd25519(data []byte, privKey []byte) ([]byte, error) {
	ret := _m.Called(data, privKey)

	if len(ret) == 0 {
		panic("no return value specified for SignEd25519")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return rf(data, privKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(data, privKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(data, privKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyEd25519 provides a mock function with given fields: data, sig, pubKey
func (_m *CryptoProvider) VerifyEd25519(data []byte, sig []byte, pubKey []byte) (bool, error) {
	ret := _m.Called(data, sig, pubKey)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEd25519")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) (bool, error)); ok {
		return rf(data, sig, pubKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) bool); ok {
		r0 = rf(data, sig, pubKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, []byte) error); ok {
		r1 = rf(data, sig, pubKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCryptoProvider creates a new instance of CryptoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCryptoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CryptoProvider {
	mock := &CryptoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
