// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	crypto "go-password-manager/internal/crypto"

	mock "github.com/stretchr/testify/mock"
)

// CryptoProvider is an autogenerated mock type for the CryptoProvider type
type CryptoProvider struct {
	mock.Mock
}

// DecryptAsymmetric provides a mock function with given fields: ciphertext, nonce, privKey
func (_m *CryptoProvider) DecryptAsymmetric(ciphertext []byte, nonce []byte, privKey []byte) ([]byte, error) {
	ret := _m.Called(ciphertext, nonce, privKey)

	if len(ret) == 0 {
		panic("no return value specified for DecryptAsymmetric")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) ([]byte, error)); ok {
		return rf(ciphertext, nonce, privKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) []byte); ok {
		r0 = rf(ciphertext, nonce, privKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, []byte) error); ok {
		r1 = rf(ciphertext, nonce, privKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecryptSymmetric provides a mock function with given fields: ciphertext, nonce, key
func (_m *CryptoProvider) DecryptSymmetric(ciphertext []byte, nonce []byte, key []byte) ([]byte, error) {
	ret := _m.Called(ciphertext, nonce, key)

	if len(ret) == 0 {
		panic("no return value specified for DecryptSymmetric")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) ([]byte, error)); ok {
		return rf(ciphertext, nonce, key)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) []byte); ok {
		r0 = rf(ciphertext, nonce, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, []byte) error); ok {
		r1 = rf(ciphertext, nonce, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeriveSymmetricKey provides a mock function with given fields: sharedSecret, senderEphemeralPub, recipientEphemeralPubKey
func (_m *CryptoProvider) DeriveSymmetricKey(sharedSecret []byte, senderEphemeralPub []byte, recipientEphemeralPubKey []byte) ([]byte, error) {
	ret := _m.Called(sharedSecret, senderEphemeralPub, recipientEphemeralPubKey)

	if len(ret) == 0 {
		panic("no return value specified for DeriveSymmetricKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) ([]byte, error)); ok {
		return rf(sharedSecret, senderEphemeralPub, recipientEphemeralPubKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) []byte); ok {
		r0 = rf(sharedSecret, senderEphemeralPub, recipientEphemeralPubKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, []byte) error); ok {
		r1 = rf(sharedSecret, senderEphemeralPub, recipientEphemeralPubKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ECDH provides a mock function with given fields: privateKey, publicKey
func (_m *CryptoProvider) ECDH(privateKey []byte, publicKey []byte) ([]byte, error) {
	ret := _m.Called(privateKey, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for ECDH")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return rf(privateKey, publicKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(privateKey, publicKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(privateKey, publicKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptAsymmetricFull provides a mock function with given fields: plaintext, pubKey
func (_m *CryptoProvider) EncryptAsymmetricFull(plaintext []byte, pubKey []byte) (crypto.AsymmetricEncryptResult, error) {
	ret := _m.Called(plaintext, pubKey)

	if len(ret) == 0 {
		panic("no return value specified for EncryptAsymmetricFull")
	}

	var r0 crypto.AsymmetricEncryptResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) (crypto.AsymmetricEncryptResult, error)); ok {
		return rf(plaintext, pubKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) crypto.AsymmetricEncryptResult); ok {
		r0 = rf(plaintext, pubKey)
	} else {
		r0 = ret.Get(0).(crypto.AsymmetricEncryptResult)
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(plaintext, pubKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptSymmetric provides a mock function with given fields: plaintext, key
func (_m *CryptoProvider) EncryptSymmetric(plaintext []byte, key []byte) ([]byte, []byte, error) {
	ret := _m.Called(plaintext, key)

	if len(ret) == 0 {
		panic("no return value specified for EncryptSymmetric")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, []byte, error)); ok {
		return rf(plaintext, key)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(plaintext, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) []byte); ok {
		r1 = rf(plaintext, key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func([]byte, []byte) error); ok {
		r2 = rf(plaintext, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GenerateEd25519KeyPair provides a mock function with no fields
func (_m *CryptoProvider) GenerateEd25519KeyPair() ([]byte, []byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateEd25519KeyPair")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func() ([]byte, []byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() []byte); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GenerateX25519KeyPair provides a mock function with no fields
func (_m *CryptoProvider) GenerateX25519KeyPair() ([]byte, []byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateX25519KeyPair")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func() ([]byte, []byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() []byte); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SignEd25519 provides a mock function with given fields: data, privKey
func (_m *CryptoProvider) SignEd25519(data []byte, privKey []byte) ([]byte, error) {
	ret := _m.Called(data, privKey)

	if len(ret) == 0 {
		panic("no return value specified for SignEd25519")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return rf(data, privKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(data, privKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(data, privKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyEd25519 provides a mock function with given fields: data, sig, pubKey
func (_m *CryptoProvider) VerifyEd25519(data []byte, sig []byte, pubKey []byte) (bool, error) {
	ret := _m.Called(data, sig, pubKey)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEd25519")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) (bool, error)); ok {
		return rf(data, sig, pubKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) bool); ok {
		r0 = rf(data, sig, pubKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, []byte) error); ok {
		r1 = rf(data, sig, pubKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCryptoProvider creates a new instance of CryptoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCryptoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CryptoProvider {
	mock := &CryptoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
