// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	devicekeys "go-password-manager/internal/config/devicekeys"

	mock "github.com/stretchr/testify/mock"
)

// DeviceKeyFileProvidor is an autogenerated mock type for the DeviceKeyFileProvidor type
type DeviceKeyFileProvidor struct {
	mock.Mock
}

// LoadDeviceKeys provides a mock function with no fields
func (_m *DeviceKeyFileProvidor) LoadDeviceKeys() (*devicekeys.DeviceKeyConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadDeviceKeys")
	}

	var r0 *devicekeys.DeviceKeyConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*devicekeys.DeviceKeyConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *devicekeys.DeviceKeyConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*devicekeys.DeviceKeyConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveDeviceKeys provides a mock function with given fields: config
func (_m *DeviceKeyFileProvidor) SaveDeviceKeys(config *devicekeys.DeviceKeyConfig) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for SaveDeviceKeys")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*devicekeys.DeviceKeyConfig) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeviceKeyFileProvidor creates a new instance of DeviceKeyFileProvidor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceKeyFileProvidor(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceKeyFileProvidor {
	mock := &DeviceKeyFileProvidor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
