// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	crypto "go-password-manager/internal/crypto"

	mock "github.com/stretchr/testify/mock"
)

// DeviceKeyProvider is an autogenerated mock type for the DeviceKeyProvider type
type DeviceKeyProvider struct {
	mock.Mock
}

// GetAppUser provides a mock function with no fields
func (_m *DeviceKeyProvider) GetAppUser() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppUser")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetDeviceName provides a mock function with no fields
func (_m *DeviceKeyProvider) GetDeviceName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetEncryptionDeviceKey provides a mock function with no fields
func (_m *DeviceKeyProvider) GetEncryptionDeviceKey() (*crypto.DeviceKey, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEncryptionDeviceKey")
	}

	var r0 *crypto.DeviceKey
	var r1 error
	if rf, ok := ret.Get(0).(func() (*crypto.DeviceKey, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *crypto.DeviceKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crypto.DeviceKey)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSigningDeviceKey provides a mock function with no fields
func (_m *DeviceKeyProvider) GetSigningDeviceKey() (*crypto.DeviceKey, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSigningDeviceKey")
	}

	var r0 *crypto.DeviceKey
	var r1 error
	if rf, ok := ret.Get(0).(func() (*crypto.DeviceKey, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *crypto.DeviceKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crypto.DeviceKey)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDeviceKeyProvider creates a new instance of DeviceKeyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceKeyProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceKeyProvider {
	mock := &DeviceKeyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
