// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sharing "go-password-manager/internal/sharing"
)

// ExportProvider is an autogenerated mock type for the ExportProvider type
type ExportProvider struct {
	mock.Mock
}

// Export provides a mock function with given fields: secrets, recipientPubKey, expiryMinutes, meta
func (_m *ExportProvider) Export(secrets []sharing.ExportSecret, recipientPubKey []byte, expiryMinutes int, meta sharing.SenderMetadata) (*sharing.SecretExportBundle, error) {
	ret := _m.Called(secrets, recipientPubKey, expiryMinutes, meta)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 *sharing.SecretExportBundle
	var r1 error
	if rf, ok := ret.Get(0).(func([]sharing.ExportSecret, []byte, int, sharing.SenderMetadata) (*sharing.SecretExportBundle, error)); ok {
		return rf(secrets, recipientPubKey, expiryMinutes, meta)
	}
	if rf, ok := ret.Get(0).(func([]sharing.ExportSecret, []byte, int, sharing.SenderMetadata) *sharing.SecretExportBundle); ok {
		r0 = rf(secrets, recipientPubKey, expiryMinutes, meta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sharing.SecretExportBundle)
		}
	}

	if rf, ok := ret.Get(1).(func([]sharing.ExportSecret, []byte, int, sharing.SenderMetadata) error); ok {
		r1 = rf(secrets, recipientPubKey, expiryMinutes, meta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExportProvider creates a new instance of ExportProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExportProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExportProvider {
	mock := &ExportProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
