// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	sharing "go-password-manager/internal/sharing"

	mock "github.com/stretchr/testify/mock"
)

// ImportProvider is an autogenerated mock type for the ImportProvider type
type ImportProvider struct {
	mock.Mock
}

// ImportSecrets provides a mock function with given fields: bundle, recipientPrivateKey, recipientEphemeralPubKey
func (_m *ImportProvider) ImportSecrets(bundle *sharing.SecretExportBundle, recipientPrivateKey []byte, recipientEphemeralPubKey []byte) (*sharing.SecretImportResult, error) {
	ret := _m.Called(bundle, recipientPrivateKey, recipientEphemeralPubKey)

	if len(ret) == 0 {
		panic("no return value specified for ImportSecrets")
	}

	var r0 *sharing.SecretImportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*sharing.SecretExportBundle, []byte, []byte) (*sharing.SecretImportResult, error)); ok {
		return rf(bundle, recipientPrivateKey, recipientEphemeralPubKey)
	}
	if rf, ok := ret.Get(0).(func(*sharing.SecretExportBundle, []byte, []byte) *sharing.SecretImportResult); ok {
		r0 = rf(bundle, recipientPrivateKey, recipientEphemeralPubKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sharing.SecretImportResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*sharing.SecretExportBundle, []byte, []byte) error); ok {
		r1 = rf(bundle, recipientPrivateKey, recipientEphemeralPubKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImportProvider creates a new instance of ImportProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImportProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImportProvider {
	mock := &ImportProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
