// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"go-password-manager/internal/config/devicekeys"

	mock "github.com/stretchr/testify/mock"
)

// PEMProvider is an autogenerated mock type for the PEMProvider type
type PEMProvider struct {
	mock.Mock
}

// DecodeKeyFromPEM provides a mock function with given fields: pemBytes, keyType
func (_m *PEMProvider) DecodeKeyFromPEM(pemBytes []byte, keyType devicekeys.KeyType) ([]byte, error) {
	ret := _m.Called(pemBytes, keyType)

	if len(ret) == 0 {
		panic("no return value specified for DecodeKeyFromPEM")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, devicekeys.KeyType) ([]byte, error)); ok {
		return rf(pemBytes, keyType)
	}
	if rf, ok := ret.Get(0).(func([]byte, devicekeys.KeyType) []byte); ok {
		r0 = rf(pemBytes, keyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, devicekeys.KeyType) error); ok {
		r1 = rf(pemBytes, keyType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncodeKeyToPEM provides a mock function with given fields: key, keyType
func (_m *PEMProvider) EncodeKeyToPEM(key []byte, keyType devicekeys.KeyType) ([]byte, error) {
	ret := _m.Called(key, keyType)

	if len(ret) == 0 {
		panic("no return value specified for EncodeKeyToPEM")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, devicekeys.KeyType) ([]byte, error)); ok {
		return rf(key, keyType)
	}
	if rf, ok := ret.Get(0).(func([]byte, devicekeys.KeyType) []byte); ok {
		r0 = rf(key, keyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, devicekeys.KeyType) error); ok {
		r1 = rf(key, keyType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPEMProvider creates a new instance of PEMProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPEMProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *PEMProvider {
	mock := &PEMProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
