// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SecretsEncryptionKeyProvidor is an autogenerated mock type for the SecretsEncryptionKeyProvidor type
type SecretsEncryptionKeyProvidor struct {
	mock.Mock
}

// CreateSymmetricKey provides a mock function with given fields: keySize
func (_m *SecretsEncryptionKeyProvidor) CreateSymmetricKey(keySize int) ([]byte, error) {
	ret := _m.Called(keySize)

	if len(ret) == 0 {
		panic("no return value specified for CreateSymmetricKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]byte, error)); ok {
		return rf(keySize)
	}
	if rf, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = rf(keySize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(keySize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadOrCreateKey provides a mock function with no fields
func (_m *SecretsEncryptionKeyProvidor) LoadOrCreateKey() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadOrCreateKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSecretsEncryptionKeyProvidor creates a new instance of SecretsEncryptionKeyProvidor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsEncryptionKeyProvidor(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsEncryptionKeyProvidor {
	mock := &SecretsEncryptionKeyProvidor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
