// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "go-password-manager/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SecretsProvider is an autogenerated mock type for the SecretsProvider type
type SecretsProvider struct {
	mock.Mock
}

// GetSecretValue provides a mock function with given fields: secret
func (_m *SecretsProvider) GetSecretValue(secret *domain.Secret) (string, error) {
	ret := _m.Called(secret)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Secret) (string, error)); ok {
		return rf(secret)
	}
	if rf, ok := ret.Get(0).(func(*domain.Secret) string); ok {
		r0 = rf(secret)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.Secret) error); ok {
		r1 = rf(secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveOrUpdateSecrets provides a mock function with given fields: secrets
func (_m *SecretsProvider) SaveOrUpdateSecrets(secrets []domain.Secret) error {
	ret := _m.Called(secrets)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrUpdateSecrets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]domain.Secret) error); ok {
		r0 = rf(secrets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSecretsProvider creates a new instance of SecretsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsProvider {
	mock := &SecretsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
