// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	transport "go-password-manager/internal/transport"
)

// TransportBuilder is an autogenerated mock type for the TransportBuilder type
type TransportBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: ctx, id, cfg, local, deps
func (_m *TransportBuilder) Build(ctx context.Context, id string, cfg map[string]interface{}, local transport.DeviceDescriptor, deps transport.Dependencies) (transport.BundleTransport, error) {
	ret := _m.Called(ctx, id, cfg, local, deps)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 transport.BundleTransport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, transport.DeviceDescriptor, transport.Dependencies) (transport.BundleTransport, error)); ok {
		return rf(ctx, id, cfg, local, deps)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, transport.DeviceDescriptor, transport.Dependencies) transport.BundleTransport); ok {
		r0 = rf(ctx, id, cfg, local, deps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transport.BundleTransport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}, transport.DeviceDescriptor, transport.Dependencies) error); ok {
		r1 = rf(ctx, id, cfg, local, deps)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransportBuilder creates a new instance of TransportBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransportBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransportBuilder {
	mock := &TransportBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
