// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.2
// source: envelope.proto

package transportpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType enumerates envelope variants.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_DATA        MessageType = 1 // Carries a SecretExportBundle
	MessageType_MESSAGE_TYPE_ACK         MessageType = 2 // Acknowledgement of receipt
	MessageType_MESSAGE_TYPE_ERROR       MessageType = 3 // Error condition (optional future use)
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_DATA",
		2: "MESSAGE_TYPE_ACK",
		3: "MESSAGE_TYPE_ERROR",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_DATA":        1,
		"MESSAGE_TYPE_ACK":         2,
		"MESSAGE_TYPE_ERROR":       3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

type SecretExportPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EncryptedSecrets []byte                 `protobuf:"bytes,3,opt,name=encrypted_secrets,json=encryptedSecrets,proto3" json:"encrypted_secrets,omitempty"`
	SecretsNonce     []byte                 `protobuf:"bytes,4,opt,name=secrets_nonce,json=secretsNonce,proto3" json:"secrets_nonce,omitempty"`
	SymmetricKeyBox  []byte                 `protobuf:"bytes,5,opt,name=symmetric_key_box,json=symmetricKeyBox,proto3" json:"symmetric_key_box,omitempty"`
	Timestamp        int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Sender metadata kept minimal for transport; expand if needed.
	SenderDeviceName       string `protobuf:"bytes,8,opt,name=sender_device_name,json=senderDeviceName,proto3" json:"sender_device_name,omitempty"`
	SenderUserId           string `protobuf:"bytes,9,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`
	SenderPublicKey        []byte `protobuf:"bytes,10,opt,name=sender_public_key,json=senderPublicKey,proto3" json:"sender_public_key,omitempty"`
	SenderSigningPublicKey []byte `protobuf:"bytes,11,opt,name=sender_signing_public_key,json=senderSigningPublicKey,proto3" json:"sender_signing_public_key,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretExportPayload) Reset() {
	*x = SecretExportPayload{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretExportPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretExportPayload) ProtoMessage() {}

func (x *SecretExportPayload) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretExportPayload.ProtoReflect.Descriptor instead.
func (*SecretExportPayload) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *SecretExportPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretExportPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretExportPayload) GetEncryptedSecrets() []byte {
	if x != nil {
		return x.EncryptedSecrets
	}
	return nil
}

func (x *SecretExportPayload) GetSecretsNonce() []byte {
	if x != nil {
		return x.SecretsNonce
	}
	return nil
}

func (x *SecretExportPayload) GetSymmetricKeyBox() []byte {
	if x != nil {
		return x.SymmetricKeyBox
	}
	return nil
}

func (x *SecretExportPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SecretExportPayload) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SecretExportPayload) GetSenderDeviceName() string {
	if x != nil {
		return x.SenderDeviceName
	}
	return ""
}

func (x *SecretExportPayload) GetSenderUserId() string {
	if x != nil {
		return x.SenderUserId
	}
	return ""
}

func (x *SecretExportPayload) GetSenderPublicKey() []byte {
	if x != nil {
		return x.SenderPublicKey
	}
	return nil
}

func (x *SecretExportPayload) GetSenderSigningPublicKey() []byte {
	if x != nil {
		return x.SenderSigningPublicKey
	}
	return nil
}

type SecretExportBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *SecretExportPayload   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretExportBundle) Reset() {
	*x = SecretExportBundle{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretExportBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretExportBundle) ProtoMessage() {}

func (x *SecretExportBundle) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretExportBundle.ProtoReflect.Descriptor instead.
func (*SecretExportBundle) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *SecretExportBundle) GetPayload() *SecretExportPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SecretExportBundle) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=transportpb.MessageType" json:"type,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Bundle        *SecretExportBundle    `protobuf:"bytes,3,opt,name=bundle,proto3" json:"bundle,omitempty"`                                 // Present when type=DATA
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Present when type=ERROR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Envelope) GetBundle() *SecretExportBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *Envelope) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\vtransportpb\"\xaf\x03\n" +
	"\x13SecretExportPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x11encrypted_secrets\x18\x03 \x01(\fR\x10encryptedSecrets\x12#\n" +
	"\rsecrets_nonce\x18\x04 \x01(\fR\fsecretsNonce\x12*\n" +
	"\x11symmetric_key_box\x18\x05 \x01(\fR\x0fsymmetricKeyBox\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12,\n" +
	"\x12sender_device_name\x18\b \x01(\tR\x10senderDeviceName\x12$\n" +
	"\x0esender_user_id\x18\t \x01(\tR\fsenderUserId\x12*\n" +
	"\x11sender_public_key\x18\n" +
	" \x01(\fR\x0fsenderPublicKey\x129\n" +
	"\x19sender_signing_public_key\x18\v \x01(\fR\x16senderSigningPublicKey\"n\n" +
	"\x12SecretExportBundle\x12:\n" +
	"\apayload\x18\x01 \x01(\v2 .transportpb.SecretExportPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xb3\x01\n" +
	"\bEnvelope\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.transportpb.MessageTypeR\x04type\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x127\n" +
	"\x06bundle\x18\x03 \x01(\v2\x1f.transportpb.SecretExportBundleR\x06bundle\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage*p\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_DATA\x10\x01\x12\x14\n" +
	"\x10MESSAGE_TYPE_ACK\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\x03B:Z8go-password-manager/internal/transport/proto;transportpbb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_envelope_proto_goTypes = []any{
	(MessageType)(0),            // 0: transportpb.MessageType
	(*SecretExportPayload)(nil), // 1: transportpb.SecretExportPayload
	(*SecretExportBundle)(nil),  // 2: transportpb.SecretExportBundle
	(*Envelope)(nil),            // 3: transportpb.Envelope
}
var file_envelope_proto_depIdxs = []int32{
	1, // 0: transportpb.SecretExportBundle.payload:type_name -> transportpb.SecretExportPayload
	0, // 1: transportpb.Envelope.type:type_name -> transportpb.MessageType
	2, // 2: transportpb.Envelope.bundle:type_name -> transportpb.SecretExportBundle
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
