name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: password-manager-linux-amd64
          - os: macos-latest  
            binary: password-manager-macos-arm64
          - os: windows-latest
            binary: password-manager-windows-amd64.exe
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libc6-dev libgl1-mesa-dev xorg-dev

      - name: Build binary
        run: |
          go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/}" -o ${{ matrix.binary }} ./cmd

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.binary }}
          body: |
            ## 🚀 Release ${GITHUB_REF#refs/tags/}
            
            ### Platform Binaries
            - **Linux (x64)**: `password-manager-linux-amd64`
            - **macOS (Apple Silicon)**: `password-manager-macos-arm64`  
            - **Windows (x64)**: `password-manager-windows-amd64.exe`
            
            ### Installation
            1. Download the binary for your platform
            2. Make executable (Linux/macOS): `chmod +x password-manager-*`
            3. Run: `./password-manager-*`
            
            **Built from:** ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
